logo = "//div[contains(@class, 'Logo')]"
username_input = '//input[@id="username"]'
password_input = '//input[@id="password"]'
forgot_password_link = '//a[@href="/forgot-password"]'
login_button = '//button[@type="submit"]'
page_title = '//div[contains(@class, "Title")]'
incorrect_credentials_message = '//div[text() = "Incorrect username or password"]'
request_link = '//button[@type="submit"]'
email_input = '//input[@id="username"]'
reset_message = '//div[contains(text(), "An email has been sent")]'
empty_field_error = '//div[contains(text(), "Please fill in this field")]'
